export  const ACTIONS = {
    UPDATE_JOURNAl :  'UPDATE_JOURNAl',
    SET_USER : 'SET_USER',
    SET_MESSAGE : 'SET_MESSAGE',
    SET_FEATURED : 'SET_FEATURED',
    CLEAR_JOURNAL : 'CLEAR_JOURNAL',
    EDIT_ENTRY : 'EDIT_ENTRY',
    TOGGLE_EDIT : "TOGGLE_EDIT",
    UPDATE_EDIT: "UPDATE_EDIT"
}